### ISSUE TITLE
Invert sign of a numeric variable

### ISSUE THREAD

**Issue by EmanueleBonin** [neilsf/XC-BASIC#126] opened 2020-10-29 13:17 UTC
If i use this syntax :
let v=1
let v=-v

Compiler return an error like this:
failure at line 1, col 5, after " v=1\nlet v" expected "anything but \"=\""

the workaround is :
let v=1
let v=0-v

exists a more elegant way or is this the right way ?

**Comment by neilsf** [comment] 2020-10-29 13:42
The unary - operator was dropped somewhere in version 0.9 and has not been re-implemented since.
Hopefully I can add it again in version 3.

**Comment by neilsf** [comment] 2020-11-15 09:10
Duplicate of #40

**Closed by neilsf** 2020-11-15 09:10 UTC
