### ISSUE TITLE
Memory information message

### ISSUE THREAD

**Issue by Majikeyric** [neilsf/XC-BASIC#78] opened 2019-11-16 08:14 UTC
The Data start-end addresses can be reversed if the Data length is short.

example:

Code : ....
Data :  $2aa3 - $2aa2
Variables* .....

**Comment by neilsf** [comment] 2019-11-16 08:20
Thanks. This is to be fixed with the next release.

**Comment by neilsf** [comment] 2019-12-06 06:53
Sorry I can't reproduce this. I have tried with different length of data, even with a single byte and it always showed the correct addresses.

**Closed** 2019-12-09 06:47 UTC
Labels: bug, minor
