### ISSUE TITLE
INPUT leaves a cursor on screen

### ISSUE THREAD

**Issue by oliverhermanni** [neilsf/XC-BASIC#71] opened 2019-09-20 14:50 UTC
If the INPUT cursor is visible when pressing `ENTER` the cursor (more like the inverted space) stays on the screen. 

![image](https://user-images.githubusercontent.com/1240179/65336411-9cab7280-dbc6-11e9-8af6-c136471d22f5.png)

**Comment by neilsf** [comment] 2019-09-20 19:14
I remember this was an issue in an earlier v2.0 version but it has been fixed since then and now I can't reproduce. Can you please post a piece of code? Thanks.

**Comment by neilsf** [comment] 2019-09-20 19:27
Nevermind, I could reproduce.

**Comment by neilsf** [comment] 2019-12-11 20:37
Fixed in the upcoming v2.2

**Closed by neilsf** 2019-12-11 20:37 UTC
Labels: bug
